apiVersion: apps/v1
kind: Deployment
metadata:
  name: online-shop-deployment
  labels:
    app: online-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: online-shop
  template:
    metadata:
      labels:
        app: online-shop 
    spec:
      containers:
      - name: online-shopserver
        image: sudarshandn/ecommerce_01:latest
        ports:
        - containerPort: 3000
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: online-shop-service
spec:
  selector:
    app: online-shop 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 3000
    nodePort: 31110
